"""add planting year, status, and pemupukan terakhir

Revision ID: 3cc5f84e2b28
Revises: edabf1f4f250
Create Date: 2023-03-11 02:50:59.309518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3cc5f84e2b28'
down_revision = 'edabf1f4f250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('planting_date', sa.DateTime(), nullable=True))
    op.add_column('trees', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trees', sa.Column('pemupukan_terakhir', sa.DateTime(), nullable=True))
    op.drop_column('trees', 'planting_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('planting_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trees', 'pemupukan_terakhir')
    op.drop_column('trees', 'status')
    op.drop_column('trees', 'planting_date')
    # ### end Alembic commands ###
