"""add planting year for each tree

Revision ID: edabf1f4f250
Revises: 6405eaa2a9f0
Create Date: 2023-03-09 10:48:36.985486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'edabf1f4f250'
down_revision = '6405eaa2a9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('planting_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'planting_year')
    # ### end Alembic commands ###
